name: logistics_landing_page
description: "A logistics company landing page"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.3
  dropdown_button2: ^2.3.8
  responsive_builder: ^0.7.0
  flutter_animate: ^2.1.0
  avatar_glow: ^2.0.2
  intl: ^0.18.1
  flutter_riverpod: ^2.3.6
  flutter_svg:
  flutter_spinkit: ^5.2.0
  flutter_svg_provider: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: PPNeueMontreal
      fonts:
        - asset: assets/fonts/PPNeueMontreal-Bold.otf
        - asset: assets/fonts/PPNeueMontreal-Book.otf
        - asset: assets/fonts/PPNeueMontreal-Italic.otf
        - asset: assets/fonts/PPNeueMontreal-Medium.otf
        - asset: assets/fonts/PPNeueMontreal-SemiBoldItalic.otf
        - asset: assets/fonts/PPNeueMontreal-Thin.otf
